fix typo
MasoniteFramework/orm-docs pull request #25
Opened 2021-05-26 14:08 UTC by erhuabushuo

2021-05-26 14:43 UTC, josephmancuso requested changes

2021-05-26 14:43 UTC, josephmancuso commented on introduction.md
> +Masonite ORM is a beatiful implementation that includes models, migrations, a query builder, seeds, command scaffolding, query scopes, eager loading, model relationships and many more features.
This should be "beautiful" actually

2021-06-01 12:47 UTC, erhuabushuo commented on introduction.md
> +Masonite ORM is a beatiful implementation that includes models, migrations, a query builder, seeds, command scaffolding, query scopes, eager loading, model relationships and many more features.
done

2021-06-01 13:55 UTC, josephmancuso approved these changes

2021-06-01 13:55 UTC, merged